apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: jenkins-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: jenkins-pv