apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: jenkins-ingress
    namespace : jenkins
spec:
  rules:
  - host: jenkins.datalabs.tapestry.com
    http:
      paths:
      - path:
        backend:
          serviceName: jenkins
          servicePort: 8080