master:
  image: "srikavyakola/jenkins-docker"
  tag: "latest"
  runAsUser: 0
  numExecutors: 2
  enableXmlConfig: true
  resources:
    requests:
      cpu: "1000m"
      memory: "1024Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  containerEnv:
    - name: DOCKER_HOST 
      value: tcp://localhost:2375 
  installPlugins:
    - kubernetes:1.27.3
    - workflow-job:2.40
    - workflow-aggregator:2.6
    - credentials-binding:1.24
    - git:4.4.5
    - configuration-as-code:1.45
  additionalPlugins:
    - role-strategy:3.1
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1beta1"
    hostName: jenkins.datalabs.tapestry.com
  #nodeSelector: {"name" : "jenkins-worker"}
  initializeOnce: false

  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server. Please contact skola@tapestry.com for any issues.
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  name: "admin"
          authorizationStrategy:
            roleBased:
              roles:
                global:
                  - name: "admin"
                    description: "Jenkins administrators"
                    permissions:
                      - "Overall/Administer"
                    assignments:
                      - "admin"
                  - name: "developers"
                    description: "Read-only users"
                    permissions:
                      - "Overall/Read"
                      - "Job/Read"
                      - "Job/Read"
                    assignments:
                      - "authenticated"   
  sidecars:
    other:
    - name: dind-daemon 
      image: docker:1.12.6-dind 
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 20m
          memory: 256Mi
      securityContext: 
        privileged: true 
      volumeMounts: 
      - name: docker-graph-storage
        mountPath: /var/lib/docker
persistence:
  existingClaim: jenkins-pvc
  accessMode: "ReadWriteMany"
  volumes: 
  - name: docker-graph-storage 
    emptyDir: {}
agent:
  enabled: false